server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lpgm-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
  - job_name: dispatch-ui
    static_configs:
      - targets:
          - localhost
        labels:
          job: dispatch-ui
          __path__: /var/lib/docker/containers/5c6f684fdd730b0af48e6e9a6da5126c1fcfa8f69a8725ef39664439bda07dae/5c6f684fdd730b0af48e6e9a6da5126c1fcfa8f69a8725ef39664439bda07dae-json.log

