services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - env=dev
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - monitor

volumes:
  jenkins_home:

networks:
  monitor:
    external: true
